# syntax=docker/dockerfile:1
ARG RUBY_VERSION
FROM ruby:${RUBY_VERSION}-slim
WORKDIR /rails
ENV RAILS_ENV=development BUNDLE_PATH=/usr/local/bundle
RUN apt-get update -qq && apt-get install --no-install-recommends -y build-essential git libpq-dev libsqlite3-dev libvips curl nodejs npm && rm -rf /var/lib/apt/lists/*
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
